packages:
  - apps/*
  - packages/*

catalog:
  typescript: ^5.9.3
  wrangler: ^4.62.0

ignoredBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - sharp
  - workerd

onlyBuiltDependencies:
  - supabase
